#!/bin/sh

XBPS_ARCH=aarch64 xbps-rindex --signedby "RRVL" --privkey ~/.ssh/rrvl.pem --sign hostdir/binpkgs/rrvl
XBPS_ARCH=armv7l xbps-rindex --signedby "RRVL" --privkey ~/.ssh/rrvl.pem --sign hostdir/binpkgs/rrvl

XBPS_ARCH=aarch64 xbps-rindex --privkey ~/.ssh/rrvl.pem --sign-pkg hostdir/binpkgs/rrvl/*.xbps

rsync -av --delete hostdir/binpkgs/rrvl/* eple.us:www/rrvl
