#!/bin/sh

#set -xv 

repo=$(realpath hostdir/binpkgs/rrvl)

rm -f $repo/*.sig

for arch in aarch64 armv7l; do
    rm -f $repo/$arch-repodata

    XBPS_ARCH=$arch xbps-rindex -a $repo/*$arch.xbps
    XBPS_ARCH=$arch xbps-rindex --signedby "RRVL" --privkey ~/.ssh/rrvl.pem --sign $repo
    XBPS_ARCH=$arch xbps-rindex --privkey ~/.ssh/rrvl.pem --sign-pkg $repo/*.$arch.xbps

    #XBPS_ARCH=$arch xbps-rindex -c $repo
    #XBPS_ARCH=$arch xbps-rindex -r $repo
done


rsync -av --delete $repo/* eple.us:www/rrvl
